### ISSUE TITLE
Broken in NextJs

### ISSUE THREAD

**Issue by huntedman** [ivanhofer/typesafe-i18n#133]
### Describe the bug

I started a new nextjs project and followed the install instructions, and somehow it doesn't work.

It's failing at runtime with an error "TypeError: e is undefined".

I also added a link to a repo with my setup. Am I doing something wrong with the scripts?

### Reproduction

https://github.com/huntedman/broken-nextjs-i18n

**Comment by ivanhofer** [comment]
This error was introduced in version `2.54.0`. Until I am able to fix it, please use `2.53.2`.
You can install it by running `npm i typesafe-i18n@2.53.2`

**Comment by ivanhofer** [comment]
should be fixed in version `2.54.3`
