### ISSUE TITLE
2.53.2 breaks return type of i18nObject

### ISSUE THREAD

**Issue by purge** [ivanhofer/typesafe-i18n#136]
### Describe the bug

before `2.53.2` i18nObject return type is correctly equal to generated `TranslationFunctions`. 
in > `2.53.2` it returns the wrong type

### Reproduction

run i18nObject in pre / post version.

**Comment by ivanhofer** [comment]
@purge could you please provide me some more info?
e.g. the code you are using

**Comment by ivanhofer** [comment]
this issue only occurred on TypeScript > 4.5.x

it was fixed in version `2.55.1`

**Comment by purge** [comment]
Sorry just got this - Thanks for the fix!
