### ISSUE TITLE
 Setup CLI | Support _pnpm_ as package manager

### ISSUE THREAD

**Issue by EstebanBorai** [ivanhofer/typesafe-i18n#138]
### Describe the bug

Running:

```bash
pnpm --package=typescript --package=typesafe-i18n dlx typesafe-i18n --setup-auto
```

Freezes during installation.

### Reproduction

`pnpm --package=typescript --package=typesafe-i18n dlx typesafe-i18n --setup-auto`

### Logs

```shell
pnpm --package=typescript --package=typesafe-i18n dlx typesafe-i18n --setup-auto
Packages: +2
++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/estebanborai/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 2, reused 2, downloaded 0, added 2, done

/private/var/folders/_4/g6lk29j10nv2f9tj1phdh56w0000gn/T/dlx-3504/5:
+ typesafe-i18n 2.55.1
+ typescript 4.5.3
[typesafe-i18n] version 2.55.1
[typesafe-i18n] generated config file: '.typesafe-i18n.json'
[typesafe-i18n] installing dependencies ...
```

### Config

```json
N/A
```

### Additional information

I have a branch with some work done in the issue where support for pnpm is provided by doing `pnpm add typesafe-i18n`
if there's a `pnpm-lock.yml` file available.

https://github.com/EstebanBorai/typesafe-i18n/commit/a5756d33f25ed7098d6515e3a24b6af70ec9ee9f

If this meet the requirements, I'm open to add the corresponding docs and open a PR later today!

Have a nice day, and thanks for your work on this project.

**Comment by ivanhofer** [comment]
Hi @EstebanBorai thanks for reporting the bug and providing a PR.

I find it strange that the normal `npm` command freezes. I thought it will probably just create a `package.lock` file for unsupported package managers.

I will take a look at your PR 👍

**Comment by EstebanBorai** [comment]
> Hi @EstebanBorai thanks for reporting the bug and providing a PR.
> 
> I find it strange that the normal `npm` command freezes. I thought it will probably just create a `package.lock` file for unsupported package managers.
> 
> I will take a look at your PR 👍

Thanks! Of course I've landed a PR and also took in consideration the comment in the commit.

**Comment by ivanhofer** [comment]
Thanks @EstebanBorai for your help.
I have changed a few things and merged it.
You can try it in version `2.56.0`.
