### ISSUE TITLE
How to get an entire array

### ISSUE THREAD

**Issue by GLAD-DE** [ivanhofer/typesafe-i18n#152]
### Describe the bug

I have an array with 4 items that I want to display. Before using this package, which is awesome, by the way, I had the array defined like this: ```let arr = ['item 1', 'item 2', 'item 3', 'item 4']```. This allowed me to use the ```{:each}``` block provided by svelte for easy output. Unfortunately, I have not found a way to get the entire array at once when using typesafe-i18n. Instead I have to use ```{$LL.arr["0"]()}``` to ```{$LL.arr["4"]()}```, which get's annoying pretty quick.

Am I missing something or is there no way to get an entire array/object?

### Reproduction

[I adapted the sveltekit example.](https://github.com/GLAD-DE/typesafe-i18n-example)

### Config

```json
{
   "$schema": "https://unpkg.com/typesafe-i18n@2.58.0/schema/typesafe-i18n.json",
   "adapter": "svelte"
}
```

**Comment by ivanhofer** [comment]
Hi @GLAD-DE,
thanks for creating this issue. `typesafe-i18n` uses a [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to access the translations. By default it doesn't support iterating over it's contents.
I will think about a way to make you use-case possible :)

**Comment by GLAD-DE** [comment]
I may have found a way to enable this.

The downside of my approach is that there can't be more than one object with the same key in the same level since the first object would shaddow the following ones.

The links all lead to the same code
- [Link to jsfiddle](https://jsfiddle.net/a0h8vw5k/2/)
- [Link to OneComplier](https://onecompiler.com/javascript/3xqr4fwpy)

**Comment by ivanhofer** [comment]
iterating over arrays should now work with version `2.60.1`.
```ts
const en: BaseTranslation = {
   arr: [
      'item 1',
      'item 2'
   ]
}
```

```svelte
<ul>
   {#each Object.values($LL.arr) as entry}
      <li>{entry()}</li>
   {/each}
</ul>

<!-- output:
<ul>
   <li>item 1</li>
   <li>item 2</li>
</ul>
-->
```

@GLAD-DE could you please confirm?

**Comment by GLAD-DE** [comment]
I can confirm that it is working as expected :)
Thank you very much for adding this feature so fast!
