### ISSUE TITLE
Calling translations with .apply or .call

### ISSUE THREAD

**Issue by moufmouf** [ivanhofer/typesafe-i18n#156]
### Describe the bug

I'm using typesafe-i18n (which is by the way excellent) with Svelte.

Everything is working great. I can write translations with

```
$LL.my.translation.key()
```

and it gets correctly translated.

Now, my application is using Testcafe for end-to-end test. And in Testcafe, it is translated to:

```
"my.translation.key.apply"
```

Notice the "apply" at the end of the string. The thing is Testcafe is doing some black magic to the code and adding itself its own proxys.

That should not be a `typesafe-i18n` issue... until I asked myself... what if I try to run:

```
$LL.my.translation.key.apply([])
```

With the current implementation of `typesafe-i18n`, `typesafe-i18n` looks for the "my.translation.key.apply" key.
The syntax is ambiguous. In my opinion, it could also mean that we want to call the "$LL.my.translation.key" method.

Same remark applies for the "call" method.

```
$LL.my.translation.key.call([])
```

So this is both an issue and a question.

Shouldn't the `get` method of the proxy used by `typesafe-i18n` not ignore "apply" and "call" keys? (which could be a breaking changes for users that use "apply" and "call" keys in their translations.

### Reproduction

Simply try to translate any string by using the Javascript ".apply()" method

**Comment by ivanhofer** [comment]
@moufmouf I just tested it inside a Svelte-component and I'm not sure if I have understood everything right.

When having following code:
```svelte
<script>
   $: console.log(1, $LL.HI({ name: 'a' }))
   $: console.log(2, $LL.HI.apply(this, [{ name: 'b' }]))
   $: console.log(3, $LL.HI.call(this, { name: 'c' }))
</script>
```

The output in my console is:
![image](https://user-images.githubusercontent.com/21335119/150851570-bcccd958-06e6-40bb-b3a6-e54515c6787a.png)

In my opinion this is the correct behaviour.

**Comment by ivanhofer** [comment]
Could you please tell me what version of `typesafe-i18n` you are using?
I have changed the `Proxy` implementation this weekend and I think I have fixed your problem without actually knowing this issue exists ^^

**Comment by moufmouf** [comment]
I'll give a shot at the new version! Ping @nolway

**Comment by ivanhofer** [comment]
@moufmouf did it work?

**Comment by moufmouf** [comment]
@nolway is testing it this afternoon!

**Comment by ivanhofer** [comment]
I will close this issue since the described issue is working for me. Feel free to open this issue again, if you still have problems
