### ISSUE TITLE
Sveltekit example

### ISSUE THREAD

**Issue by ohbob** [ivanhofer/typesafe-i18n#158]
### Version

8.1.2

### Describe the bug

sveltekit example isnt working due the braking changes.

### Reproduction

```
git clone https://github.com/ivanhofer/typesafe-i18n.git
cd examples/sveltekit
yarn install
yarn dev
```

### Logs

```shell
in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
Error: request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
    at Object.get request [as request] (file:///home/q/Documents/test/sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:1700:11)
    at Object.handle (/home/q/Documents/test/sveltekit/src/hooks.ts:5:48)
    at respond (file:///home/q/Documents/test/sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:1607:40)
    at file:///home/q/Documents/test/sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:1937:30
request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
Error: request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
    at Object.get request [as request] (file:///home/q/Documents/test/sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:1700:11)
    at Object.handle (/home/q/Documents/test/sveltekit/src/hooks.ts:5:48)
    at respond (file:///home/q/Documents/test/sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:1607:40)
    at file:///home/q/Documents/test/sveltekit/node_modules/@sveltejs/kit/dist/chunks/index.js:1937:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Additional information

ubuntu 20.4, firefox

**Comment by ivanhofer** [comment]
@ohbob thanks!
Here is a working SvelteKit example:
https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit

I need to update the docs to link it to this example

**Comment by ohbob** [comment]
Thank you very much!

Could you expand the example of few nested routes? I'm quite stuck on the case and do not understand how I would achieve structure like domain.com/en/random/route/one

**Comment by ivanhofer** [comment]
Let me know if you need some help

**Comment by ohbob** [comment]
Not really a bug, but want to understand how you handle importing static files? as the url changes, and there is no e.g. local font on the address domain/en/font.woff . I see this isnt a problem on prod where you would have links to stuff but on local, it's really pain in the ass.

**Comment by ivanhofer** [comment]
I assume you just put the files in the `static` folder and then access them in your template e.g.
```html
<img src="/logo.png" />
```
where `logo.png` is in the root of the `static` folder.
This should work also with font files.

**Comment by ohbob** [comment]
Well i'm having problem with getting local fonts loading. if you go to domain.com/en/example, it would not load a font that is being loaded like this. Because the addres from which it tries to load isn't / anymore its /en/ and at that location there is no font. any ideas ? 
```
@font-face {
font-family: 'FilsonProRegular';
src: local('FilsonProRegular'), local('FilsonProRegular'), url(FilsonProRegular.woff) format('woff');
}
