### ISSUE TITLE
Concurrent requests can cause LL store to change locale mid-flight during SSR (SvelteKit, adapter-node)

### ISSUE THREAD

**Issue by aloker** [ivanhofer/typesafe-i18n#159]
### Version

2.60.1

### Describe the bug

In SvelteKit with adapter-node, currently typesafe-i18n creates only a single LL store in memory that is used for all requests. Multiple concurrent requests may change the current locale of that store. This can cause locales to switch within one requests if another request with another locale runs concurrently, leading to completely or partially wrong translations.

### Reproduction

The code I used is based on the sveltekit example, including the hook, the __layout.svelte and the [lang] dir.

Consider this load function of a route:
```
let nextRequestId = 1;

export const load: Load = async () => {
  const requestId = nextRequestId++;
  const sample = () => get(LL).hello();

  console.log(`Request ${requestId}, before API call:`, sample());

  await someExpensiveRequest();

  console.log(`Request ${requestId}, after API call :`, sample());

  return {
    props: {
      val: sample()
    }
  };
};
```

Let's say we have to visistors, one at http://localhost:3000/en, the other at http://localhost:3000/de

When request come in sequentially, the server side output would be something like:

```
Request 1, before API call: Hello in English
Request 1, after API call : Hello in English
Request 2, before API call: Hallo in Deutsch
Request 2, after API call : Hallo in Deutsch
``` 

But if http://localhost:3000/de is visisted before "someExpensiveRequest" resolves, we'd see this:

```
Request 3, before API call: Hello in English
Request 4, before API call: Hallo in Deutsch
Request 3, after API call : Hallo in Deutsch
Request 4, after API call : Hallo in Deutsch
```

That is, request 4 changes the locale and that's the locale that is then used by the older request 3 (which started in English).

### Logs

```shell
See above
```

### Config

```json
{
   "adapter": "svelte",
   "$schema": "https://unpkg.com/typesafe-i18n@2.60.1/schema/typesafe-i18n.json"
}
```

### Additional information

The issue is obviously caused by the fact that there's a single store in memory that can be changed concurrently by multiple in-flight requests. It would probably an idea to have one store in memory for each locale and somehow "attach" the correct one to each request. 

I've done something in the past using i18next where the correct store is selected in the root __layout and then passed to the components via context (https://svelte.dev/docs#run-time-svelte-setcontext) and to other load functions via "stuff" (https://kit.svelte.dev/docs#loading-output-stuff). It wasn't very beautiful tbh, but it worked. Maybe you can come up with something more elegant.

**Comment by ivanhofer** [comment]
Oh, right 🙈 I actually thought that SvelteKit handles concurrent users.
This is something I need to check in detail. Thanks for pointing this out.

**Comment by ivanhofer** [comment]
@aloker I now have tried a few things and the following solution works for me.
It's in a WIP state so it's not so elegant right now:

1. Replace the contents of `src/i18n/i18n.svelte.ts` with the following code:
```ts
import { getI18nSvelteStore } from 'typesafe-i18n/adapters/adapter-svelte';
import type { Locales, Translation, TranslationFunctions, Formatters } from './i18n-types'
import { baseLocale, getTranslationForLocale } from './i18n-util'
import { initFormatters } from './formatters'
import { derived, get, writable } from 'svelte/store';

const { initI18n: init, setLocale, isLoadingLocale, locale: _locale, LL: _LL } = getI18nSvelteStore<Locales, Translation, TranslationFunctions, Formatters>()

const cache = {} as Record<Locales, { LL: TranslationFunctions, locale: Locales }>

const initI18n = async (locale: Locales = baseLocale) => {
   await init(locale, getTranslationForLocale, initFormatters)
   cache[locale] = { LL: get(_LL), locale: get(_locale) }
}

export const restoreI18n = (l: Locales) => {
   const x = cache[l]
   __LL.set(x.LL)
   __locale.set(x.locale)
}

const __LL = writable(get(_LL))
_LL.subscribe(v => __LL.set(v))

const __locale = writable(get(_locale))
_locale.subscribe(v => __locale.set(v))

const LL = derived([__LL], (v) => v)
const locale = derived([__locale], (v) => v)

export { initI18n, setLocale, isLoadingLocale, locale, LL }

export default LL
```

2. Temporarely set the [`generateonlytypes`](https://github.com/ivanhofer/typesafe-i18n#generateonlytypes) option to `true`, so the generator doesn't override your modified `i18n-svelte.ts` file

3. Then call `fixI18n` inside the "normal" `script`-tag (**not** in `context="module"`) of your root `__layout` component.

**This should block the correct store until everthing is rendered for that request.**

If you are accessing translations inside the load function, you would need to make sure that you also call `fixI18n` before accessing the translations. Or to make your life easier, make a `get(LL)` inside the root `__layout` page and pass it into `stuff` and use the `LL` from the `stuff` inside load functions.

Let me know if this works for you or you need some help.

**Comment by ivanhofer** [comment]
I will refactor how `typesafe-i18n` handles loading of locales in the next major release.
It was always a bit of a pain-point that loading the locale and using the translations is so deeply coupled.
By splitting both parts, we can get rid of some limitations and will have a more elegant solution to the problem described by you.
This would also make the implementation of #113 a easier.

**Comment by ivanhofer** [comment]
@aloker I now have refactored how `typesafe-i18n` loads locales.

You can check the [latest commit](https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/commit/2eca55e82b93b2177903cc7ef68b3c4e3d0a3709) I have made to the `svelte-kit` example to see what has changed.
Most of the changes are beeing made when installing version 3 and running the `generator`.
You then just would need to manually change these files:
 - [src/lib/LocaleSwitcher.svelte](https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/commit/2eca55e82b93b2177903cc7ef68b3c4e3d0a3709#diff-0e86aa1dd2b390e57b82e0e32227154f36ede14d1a7ffe1ca589e8ae2b55f508)
- [src/routes/__layout.svelte](https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/commit/2eca55e82b93b2177903cc7ef68b3c4e3d0a3709#diff-c3a76f211b02106e458d330c6c4dfb09844e51487170b2300cf76913360eda47)
- [src/i18n/formatters.ts](https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/commit/2eca55e82b93b2177903cc7ef68b3c4e3d0a3709#diff-c27aedcd05678e156b35111711d781bb823ae4aab0dfd8d283c527346a5234b7)

Please visit the [release post](https://github.com/ivanhofer/typesafe-i18n/discussions/163) for more information.

**Comment by aloker** [comment]
Thanks for your fast response! I didn't have the opportunity to test it, but I'll check it out ASAP. Keep up the great work!
