### ISSUE TITLE
Dynamic translation strings?

### ISSUE THREAD

**Issue by Badlapje** [ivanhofer/typesafe-i18n#165]
Using typesafe-i18n in Svelte, with Sveltekit.

Is it possible to have a dynamic translation string.

Example:

I have a component like this:
```html
<section class="gls__introBlock gls__introBlock-{type}">
    <h2>{$LL[title]()}</h2>
    <p>{$LL[description]()}</p>
</section>
``` 

I compose the title & description like that, based on the type prop passed to the component:
```js
    const title = `fds.${type}.title`
    const description = `fds.${type}.description`
```

This doesn't work.  Nor can i find another way of accomplishing this.  Is this not possible currently, or am i doing something wrong?
Not sure if this is a common usecase, but when creating re-usable components, it's a big help to be able to do something like this.

**Comment by Badlapje** [comment]
Alright, i can do this with a switch case it seems, though that makes the translation strings less readable, instead of:
```js
fds: {
  notHome: {
    title: 'Ben je niet thuis?',
    description: 'De bezorg(st)er vindt het fijn als je een alternatief doorgeeft. Zo kan hij/zij weer lekker vlot verder.'
  }
},
```

i can do this:

```js
fds: {
  title: '{type|{notHome: Ben je niet thuis?, home: Ben je thuis?}',
  description: '{type|{notHome: De bezorg(st)er vindt het fijn als je een alternatief doorgeeft. Zo kan hij/zij weer lekker vlot verder., home: Tof bij jou te leveren.}',
},
```

But that's far less readable.  It can be made a more readable like below, but for anyone not used to the library it's still a tad weird:
```js
fds: {
  title: '{type|{' +
	  'notHome: Ben je niet thuis?,' +
	  ' home: Ben je thuis?' +
	  '}',
  description: '{type|{' +
	  'notHome: De bezorg(st)er vindt het fijn als je een alternatief doorgeeft. Zo kan hij/zij weer lekker vlot verder.,' +
	  ' home: Tof bij jou te leveren.' +
	  '}',
},
```

I imagine this use case is common enough to warrant a more readable solution somehow, but not sure how to go about it and it does work for now.  If you want to just go with the switch case solution, i'd be happy to create a PR to document it?

**Comment by ivanhofer** [comment]
@Badlapje you could certainly do it with the `switch` functionality, but you already have seen that this is not ideal.

I would do it like this:

1. define your translations
```ts
// i18n/en.ts
import type { BaseTranslation } from '../i18n-types'

const en: BaseTranslation = {
   fds: {
      home: {
         title: 'fds home title',
      },
      notHome: {
         title: 'fds notHome title',
      }
   }
}

export default en
```
 2. use it in your components
```svelte
<script lang="ts">
   // Component.svelte

   import LL from '$i18n/i18n-svelte'
   import type { Translation } from '$i18n/i18n-types'

   let type: keyof Translation['fds'] = 'home'

   // just for testing if it works for both cases
   const toggle = () => type  = type === 'home' ? 'notHome': 'home'
</script>

<button on:click={toggle}>toggle</button>
<p>
   {type} : {$LL.fds[type].title()}
<p>
```

Instead of concatenating the key as a string, you need to access each level of your translation object individually (sorry, I don't know how to describe this).
In my examply you can see that I manually typed the `type` variable
```ts
let type: keyof Translation['fds'] = 'home'
```
You should also do this! If you don't type it, you will loose the typesafety features of the translation function.
You could either use the `Translation` type or define them manually like this:
```ts
let type: 'home' | 'notHome' = 'home'
```

Hope this helps :)

**Comment by Badlapje** [comment]
This works like a charm indeed.  I'll be writing up a PR sometime later today to amend the docs with this solution 👍

**Comment by ivanhofer** [comment]
I have added a [new section](https://github.com/ivanhofer/typesafe-i18n#how-can-i-access-a-translation-dynamically) to the FAQs.
