### ISSUE TITLE
Missing index.d.ts in importer

### ISSUE THREAD

**Issue by Achaak** [ivanhofer/typesafe-i18n#167]
### Version

3.1.1

### Describe the bug

Missing index.d.ts in importer

![image](https://user-images.githubusercontent.com/39270779/152562612-7e7badc0-e41d-4395-b8bb-08ac5347651d.png)
![image](https://user-images.githubusercontent.com/39270779/152562655-5fbe949d-9b5b-4289-9013-113808fd8553.png)

### Reproduction

Install last version 😂

**Comment by ivanhofer** [comment]
Oh, I missed something in my latest refactoring.
It is fixed in version `3.1.2`
