### ISSUE TITLE
Not displaying translations after upgrade 3.0.0+ version

### ISSUE THREAD

**Issue by shadoworion** [ivanhofer/typesafe-i18n#172]
### Version

3.0.0+

### Describe the bug

Not displaying translations after upgrade 3.0.0+ version.
React 17 + Typescript 4.5.5 + Vite 2.8.1.

Every version after 3.0.0 doesn't work.
I checked 3.0.0, 3.1.0, 3.1.1, 4.0.0, 4.1.0, 4.1.1 versions.
I have no errors.

The module generates all files successfully. But it doesn't show strings anywhere after render.

Version 2.60.2 and older work correctly.

### Reproduction

https://github.com/shadoworion/typesafe-bug

### Logs

```shell
No errors
```

### Config

```json
{
  "adapter": "react",
  "baseLocale": "he"
}
```

**Comment by ivanhofer** [comment]
@shadoworion did you take a look at the migration guide mentioned in the Changelog?
https://github.com/ivanhofer/typesafe-i18n/discussions/163

**Comment by shadoworion** [comment]
> @shadoworion did you take a look at the migration guide mentioned in the Changelog? #163

Yes, but I don't understand how it helps me...

Is this initialize not enough?

```typescript
ReactDOM.render(
  <TypesafeI18n locale="he">
    <App />.....
```

Also, after I added this code, it didn't work.

```typescript
  useEffect(() => {
    (async () => {
      await loadLocaleAsync("he");
    })();
  }, []);
```

Maybe I miss something?

**Comment by ivanhofer** [comment]
You first would need to load the locale, then initialize it. (In theory you could also initialize it first and then load the locale, but this would trigger some reflow of the website, which is not a good user experience).

Your code snippets look good. Do you want to take another look at the `react` example: https://github.com/ivanhofer/typesafe-i18n/blob/main/examples/react/src/App.tsx
Or share your repo?

**Comment by shadoworion** [comment]
Ok, thank you! It worked now!

**Comment by ivanhofer** [comment]
Great! What was wrong? Do I need to add something to the migration guide?

**Comment by shadoworion** [comment]
> Great! What was wrong? Do I need to add something to the migration guide?

This example is excellent (https://github.com/ivanhofer/typesafe-i18n/blob/main/examples/react/src/App.tsx)

My problem was -
This code (in main.tsx): 
```typescript
<TypesafeI18n locale={detectedLocale}>...
```
Before this (in App.tsx): 
```typescript
	useEffect(() => {
		loadLocaleAsync(detectedLocale).then(() => setWasLoaded(true))
	}, [])
```

So I just changed one to another
