### ISSUE TITLE
Support for sveltekit

### ISSUE THREAD

**Issue by ivanhofer** [ivanhofer/typesafe-i18n#18]
Because of https://github.com/vitejs/vite/issues/2579 it is currently not possible to use `typesafe-i18n` inside `sveltekit` applications.

A workaround is:
 - disabling `ssr` inside `svelte.config.cjs`
 - manually change `export{u as getI18nSvelteStore};` to `export const getI18nSvelteStore = u;` inside `node_modules\typesafe-i18n\adapters\adapter-svelte.js`

**Comment by ivanhofer** [comment]
was fixed with version 2.31.0

**Comment by Evertt** [comment]
Sorry, but how does one get the generator to work with Sveltekit? I see there's a page about Svelte / Sveltekit / Sapper, but there's no mention of Vite in there and I don't know how to configure Vite to run the generator...

**Comment by ivanhofer** [comment]
Hi @Evertt,
please take a look at this section: https://github.com/ivanhofer/typesafe-i18n#node-process
I will need to update the svelte-Readme, since with svelte-kit, the `node-process` makes more sense than the `rollup-plugin`. Thanks for pointing it out :)
