### ISSUE TITLE
Typesafety broken with version 3 and 4

### ISSUE THREAD

**Issue by GLAD-DE** [ivanhofer/typesafe-i18n#181]
### Version

4.1.1

### Describe the bug

My IDE (Webstorm) no longer provides auto-completion and correct paths are not recognized as such. The IDE complians ```Unresolved function or method HI()``` in the following line from the typesafe-sveltekit-example ```$LL.HI({ year: 2021 })```. This is true for all valid references to $LL.

The IDE marks valid LL paths in script as errors. For example the line ```return LL.HI({ year: 2021 });``` is invalid because ``` Property 'HI' does not exist on type 'Readable '.```.

The autcompletion and LL path detection worked flawlessly on version 2.

This may be related to issue #180 .

### Reproduction

Open [either the offical example](https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit) or [my example which includes a typescript file](https://github.com/GLAD-DE/typesafe-i18n-demo-sveltekit/tree/9f25e23e2a0d5ba2d38f384eee6f57eddf2fcfc4) in Webstorm.

### Config

```json
{
   "$schema": "https://unpkg.com/typesafe-i18n@4.1.1/schema/typesafe-i18n.json",
   "adapter": "svelte"
}
```

**Comment by ivanhofer** [comment]
@GLAD-DE in version 3 I have changed the way how translations are accessed on the svelte store.
Please see the solution here: #180

**Comment by GLAD-DE** [comment]
In this issue I am refering to accessing LL from svelte components while #180 refers to typescript files.

In the migration guide #163 you state that ```if you are using the svelte adapter and are using the LL store outside of Svelte components you need to make sure you are accessing the store correctly [via get]```.

Should all access, including those in svelte components, be via get?

**Comment by GLAD-DE** [comment]
> In this issue I am refering to accessing LL from svelte components while #180 refers to typescript files.
> 
> In the migration guide #163 you state that ```if you are using the svelte adapter and are using the LL store outside of Svelte components you need to make sure you are accessing the store correctly [via get]```.
> 
> Should all access, including those in svelte components, be via get?

Accessing LL from svelte components works with autocomoletion only if ```get``` is used. I recommend updating #163 to state that **all** access to LL should be via get.

**Comment by ivanhofer** [comment]
@GLAD-DE the Svelte compiler handles automatic subscribing to stores. So in Svelte components you can use
`$LL` to access the value of the store directly. In all other files that don't get transformed from the Svelte compiler, you need to read the value from the store either via a manual `subscribe` or by using the [`get(LL)` function](https://svelte.dev/docs#run-time-svelte-store-get).

```ts
LL // => should be of type `Readable<TranslationFunctions>`
$LL // => should be of type `TranslationFunctions`
get(LL) // => should be of type `TranslationFunctions` 
```

If TypeScript types are not working in Webstorm, I assume it is not the fault of `typesafe-i18n` so maybe you want to try out creating a simple store yourself and see if the types are working there.
