### ISSUE TITLE
Typescript compilation fail when using localized switch cases

### ISSUE THREAD

**Issue by phil714** [ivanhofer/typesafe-i18n#183]
### Version

2.52.2

### Describe the bug

Hello,

I'm trying to use the switch case feature but can't seem to wrap my head around how this is working. I'm not really sure if this is a bug or not but I'm unable to use it. 

I want to have a string display either Day or Night based on the enum sent in the string. I'm basically moving the "if" from the code to the translation because every time we need to display this string, we would need to add the same if (and maybe worse if we ever add more choices). The problem is that, the typing generated in other languages like french doesn't seem to work because the content of the switch case is also localized. The typing doesn't seem to recognize that there can be other values.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/7584581/154697284-66c394d6-8b49-4bc9-9dd5-32b7baa3d1ce.png">
<img width="951" alt="image" src="https://user-images.githubusercontent.com/7584581/154698168-8fa83f42-37e0-452c-bfcc-0419ea27a642.png">

I thought this might be an issue with me adding a type to my string because I haven't seen this in the example but even the example doesn't seems to work.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/7584581/154699264-a83d962f-9c2f-4d06-8453-d6a4e470aaf5.png">

Also let me know if this is a problem on my end and not a bug but I would think something is missing in the doc then.

### Reproduction

1. Add a translation like `photoAdded:
          '{username:string} added a new photo to {gender|{male: his, female: her, *: their}} stream.' in your base file.
2. Add another translation like `photoAdded:
          '{username} a ajouté une nouvelle photo a {gender|{male: son, female: sa, *: their}} stream.' in a translation file.
3. Typescript will display an error in your translation file that the typings dont match

My full code not working
```
// src/i18n/en/index.ts
view: '{view: ViewType|{day: Day, night: Night}}',

// src/i18n/fr/index.ts
view: '{view|{day: Jour, night: Nuit}}',

// src/i18n/customTypes.ts
export type ViewType = 'night' | 'day';
```

Let me know if you need a repository but I think this is straightforward enough

### Logs

```shell
Error message for my case


(property) 'view': `${string}{view|day: Day, night: Night}${string}`
{view|{day: Day, night: Night}}

@param view

Type '"{view|day:Jour,night:Nuit}"' is not assignable to type '`${string}{view|day: Day, night: Night}${string}`'.ts(2322)
i18n-types.ts(77, 5): The expected type comes from property 'view' which is declared here on type '{ view: `${string}{view|day: Day, night: Night}${string}`; photoAdded: RequiredParams2<"gender|male: his, female: her, *: their", "username">; }'
```

Error message for the example: 
```
(property) 'photoAdded': RequiredParams2<"gender|male: his, female: her, *: their", "username">
{username} added a new photo to {gender|{male: his, female: her, *: their}} stream.

@param gender

@param username

Type '"{username} ajouté une nouvelle photo a {gender|{male: son, female: sa, *: their}} stream."' is not assignable to type 'RequiredParams2<"gender|male: his, female: her, *: their", "username">'.ts(2322)
i18n-types.ts(83, 5): The expected type comes from property 'photoAdded' which is declared here on type '{ view: `${string}{view|day: Day, night: Night}${string}`; photoAdded: RequiredParams2<"gender|male: his, female: her, *: their", "username">; }'
```
```


### Config

```json
{
  "baseLocale": "en",
  "loadLocalesAsync": true,
  "adapter": "react",
  "outputPath": "./src/i18n/",
  "outputFormat": "TypeScript",
  "tempPath": "./node_modules/typesafe-i18n/webpack/temp-output/",
  "$schema": "https://unpkg.com/typesafe-i18n@2.52.2/schema/typesafe-i18n.json"
}
```

**Comment by ivanhofer** [comment]
Hi @phil714,
the `switch-case` functionality was added in version `2.55.0`
https://github.com/ivanhofer/typesafe-i18n/blob/main/CHANGELOG.md#2550-2021-12-05
Please update to the latest `2.x.x` version and your code should work ;)

The most recent version is `4.1.5`, so maybe you immediately want to update to that version. It contains some smaller breaking changes, you need to consider when upgrading. You can find more information in the changelog.

Also, three of your config options are set to the default value.
You can get rid of following entries if you like:
```json
{
   "baseLocale": "en",
   "outputPath": "./src/i18n/",
   "outputFormat": "TypeScript",
}
```
