### ISSUE TITLE
Cannot use `import.meta` with Sveltekit

### ISSUE THREAD

**Issue by sidvishnoi** [ivanhofer/typesafe-i18n#223]
### Version

4.5.0

### Describe the bug

I'm trying to conditionally build translation strings based on env variables in a Sveltekit project. But I cannot use `import.meta.env` which Sveltekit uses via Vite.

1. Translation doesn't work (see error in logs).
2. `TranslationFunctions` is empty `{}`.

### Reproduction

Repo: https://github.com/sidvishnoi/typesafe-i18n-demo-sveltekit-jsdoc
See: https://github.com/sidvishnoi/typesafe-i18n-demo-sveltekit-jsdoc/blob/main/src/i18n/en/index.ts

Run: `PROJECT_ID=project1 pnpm dev` and `PROJECT_ID=project2 pnpm dev`

### Logs

```sh
[typesafe-i18n] version 4.5.0
[typesafe-i18n] generating files for TypeScript version: '4.6.x'
[typesafe-i18n] options: { adapter: 'svelte', esmImports: true }
[typesafe-i18n] watcher started in: './src/i18n/'
[typesafe-i18n] ERROR: import failed for /path/to/node_modules/typesafe-i18n/temp-output/11/en/index.js SyntaxError: Cannot use 'import.meta' outside a module
[typesafe-i18n] ERROR: could not read default export from base locale file 'en'
[typesafe-i18n] ... all files are up to date
```

### Config

```JSON
{
  "adapter": "svelte",
  "esmImports": true,
  "outputPath": "./src/i18n",
  "$schema": "https://unpkg.com/typesafe-i18n@4.5.0/schema/typesafe-i18n.json"
}
```

**Comment by ivanhofer** [comment]
I see some errors from your logs. These errors should disapper when you remove the line mentioned above. Can you please run the `generator` and verify that?

**Comment by sidvishnoi** [comment]
I've removed `esmImports` and re-run `pnpm dev` (which also runs `typesafe-i18n`). Same error as before.

FWIW, adding `{ "module": "esNext", "target": "ESNext" }` in jsconfig.json/tsconfig.json doesn't change it either.

**Comment by ivanhofer** [comment]
Ah, now I understand the problem. Sorry, I haven't seen the link to your repo before.
I'll try a few things ...

**Comment by ivanhofer** [comment]
I had a few minutes of time to look into this issue.

The generator doesn't have the concept of environment variables. If you want to render conditional translations, you would need to create two keys inside your dictionary file and then call the translation function conditionally.

If you don't want to include both variants in the same dictionary you could use the [`namesapces`](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/generator#namespaces) feature and load the namespace conditionally depending on your environment variables.

**Comment by sidvishnoi** [comment]
Thanks for investigating, @ivanhofer! I think namespaces might just work right.
