### ISSUE TITLE
watcher script is not compatible with yarn workspaces

### ISSUE THREAD

**Issue by jakubwolny** [ivanhofer/typesafe-i18n#23]
After installing typesafe-i18n within one workspace, when you try to run the watcher:
`node ./node_modules/typesafe-i18n/node/watcher.js`
it does not work, since the files within node_modules are not physically located there (yarn does linking).

 ```
node ./node_modules/typesafe-i18n/node/watcher.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/jakubwolny/projects/orca/client/node_modules/typesafe-i18n/node/watcher.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```
then of course I tried to run it in the directory above (project root), but when it watches entire project, not just single workspace, and paths are all wrong. Or I haven't found a way to tell watcher to specific dir to watch i.e. 
`node ./node_modules/typesafe-i18n/node/watcher.js --dir=client`.
Also, from a perspective of a webpack user, I find it weird that I need to start another file watcher - I already have one (in webpack). So probably it's out of the scope of that issue, but having a webpack plugin could improve a Developer Experience.

So I haven't found any easy way to make it work within yarn workspace. btw. this is the most interesting i18n project I've seen in years I wanted to give a try.

**Comment by jakubwolny** [comment]
starting the watcher with:
`node ../node_modules/typesafe-i18n/node/watcher.js`
solved the issue - sometimes the simplest solutions are the best!
still, a webpack plugin could maybe make the adoption a bit easier

**Comment by ivanhofer** [comment]
Hi @jakubwolny,
thanks for your feedback :)

You can use the `outputPath` [option](https://github.com/ivanhofer/typesafe-i18n/#options) inside the `.typesafe-i18n.json`-file to set the output path for the files being generated.

The reason why no webpack plugin exists yet is because I personally use rollup and haven't had the time yet to create one. The node process is currently the fallback for users who aren't using rollup ;)

**Comment by ivanhofer** [comment]
@jakubwolny as of `typesafe-i18n` version 2.16.0 you can also start the `watcher` via a [webpack-plugin](https://github.com/ivanhofer/typesafe-i18n#webpack-plugin)

**Comment by jakubwolny** [comment]
oh wow! thank you for the update, I'll definitely try it
