### ISSUE TITLE
Types not compiled properly

### ISSUE THREAD

**Issue by high1** [ivanhofer/typesafe-i18n#249]
### Version

5.2.2

### Describe the bug

The base translated strings are added as comments in ./i18n/i18ntypes-ts and if string contains */, those are interpreted as an early close comment, and that results in an incorrect syntax.

### Reproduction

HI in en base translation was altered to have */ in int, and the types are incorrect. If it's removed, the types are properly compiled.

https://github.com/high1/soldi-typesafe-i18n

### Config

```JSON
{
   "adapter": "solid",
   "esmImports": true,
   "$schema": "https://unpkg.com/typesafe-i18n@5.2.2/schema/typesafe-i18n.json"
}
```

### Additional information

solid, unocss, typesafe-i18n - but I believe that the issue doesn't depend on libraries used.

**Comment by ivanhofer** [comment]
Thanks! The issue was fixed in version `5.2.3`.
