### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by Achaak** [ivanhofer/typesafe-i18n#263]
### Version

5.3.2

### Describe the bug

Hi !,
When I upgrade my project to React 18, I have this error.

![image](https://user-images.githubusercontent.com/39270779/162438140-39d27705-45e0-4a56-8e38-c0f5d25721b4.png)

Maybe, you should upgrade React in adapter-react

### Reproduction

Classic install with React 18

### Config

```JSON
{
   "$schema": "https://unpkg.com/typesafe-i18n@5.3.2/schema/typesafe-i18n.json",
   "baseLocale": "en",
   "adapter": "react"
}
```

**Comment by ivanhofer** [comment]
have you used this exact version of `typesafe-i18n` before upgrading to react 18?

**Comment by Achaak** [comment]
No I was in 4.5.0
I have generated the files after upgrading

**Comment by ivanhofer** [comment]
can you go back to 4.5.0 an see if it works with react 18?

**Comment by Achaak** [comment]
In 4.5.0 I have the same error

**Comment by ivanhofer** [comment]
Strange, I will try it in my example repository

**Comment by ivanhofer** [comment]
It seems that react 18 added stricter types. I now have updated the react adapter in version `5.3.3` to fix the issue.

**Comment by ivanhofer** [comment]
Here is the issue for reference: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

**Comment by Achaak** [comment]
Ok I see!
It works now, thanks! 😄
