### ISSUE TITLE
Watcher doesn't work on Linux

### ISSUE THREAD

**Issue by bartenra** [ivanhofer/typesafe-i18n#29]
`fs.watch` does not support the `recursive` option on Linux. In fact, it raises an exception when set to `true` since Node.js 14.

See https://nodejs.org/docs/latest/api/fs.html#fs_caveats

Maybe you can use https://github.com/paulmillr/chokidar which works cross-platform.

**Comment by ivanhofer** [comment]
Thanks for the PR. I was not aware that `fs` isn't multiplatform.
`chokidar` sounds like a good solution to make the experience the same on all platform. I will fix this 👍

**Comment by ivanhofer** [comment]
version 2.17.0 was released a few moments ago. The watcher should work on linux now.

**Comment by bartenra** [comment]
To be clear, the watcher won't really work for Linux since recursive watching is disabled.

But it will at least run at all. ;-)

**Comment by ivanhofer** [comment]
chokidar automatically watches recursively or did I miss someting?

**Comment by ivanhofer** [comment]
@bartenra I just tested it on WSL of my windows machine and it works also recursively. Can you please confirm that it also runs on your native Linux machine?
