### ISSUE TITLE
Define scripts with bin in package.json

### ISSUE THREAD

**Issue by bartenra** [ivanhofer/typesafe-i18n#30]
IMO it's an anti-pattern to ask users to run something directly from `node_modules`.

Instead you should define a `bin` section in package.json.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin

**Comment by ivanhofer** [comment]
Thanks @bartenra,
you're right, I also don't really like the `node_modules` solution, but haven't yet looked for a better solution.
I definitely need fix this!

**Comment by bartenra** [comment]
Nice change!

**Comment by ivanhofer** [comment]
**version 2.17.1** was released a few moments ago.

You are now able to run the watcher via:
```bash
> npx typesafe-i18n
```

or by defining a script in your `package.json` file:

```json
{
   "scripts": {
      "typesafe-i18n-watcher": "typesafe-i18n"
   }
}
```
