### ISSUE TITLE
Broken example in /packages/runtime/README.md

### ISSUE THREAD

**Issue by nonphoto** [ivanhofer/typesafe-i18n#320]
[This example](https://github.com/ivanhofer/typesafe-i18n/blob/22d2b81eabdab7ac2ee8aa48c2f7c9be34c42e18/packages/runtime/README.md?plain=1#L340-L367) appears to be broken because the signature for the `i18n` function has changed. `L.en.TODAY({ date: now })` will print nothing because the expected translation dictionary is a function.

**Comment by ivanhofer** [comment]
Thanks @nonphoto,
I have updated the example to work with the new implementation
