### ISSUE TITLE
 Named export 'i18nObject' not found

### ISSUE THREAD

**Issue by xferqr** [ivanhofer/typesafe-i18n#36]
> Named export 'i18nObject' not found. The requested module 'typesafe-i18n' is a CommonJS module

node: 15.8.0
vite: v2.2.4

	"compilerOptions": {
		"moduleResolution": "node",
		"module": "es2020",
		"lib": ["es2020"],
		"target": "es2019",
.....

package.json:   "type": "module"

**Comment by ivanhofer** [comment]
Hi @xferqr,
could you please provide me some more context?
I just created a new vite application with the same TS compiler options and it works for me.

**Comment by ivanhofer** [comment]
I'll close this ticket due to missing information on how to reproduce it
