### ISSUE TITLE
initAcceptLanguageHeaderDetector should use case-insensitive comparison

### ISSUE THREAD

**Issue by gkinsman** [ivanhofer/typesafe-i18n#451]
### Version

5.13.0

### Describe the bug

initAcceptLanguageHeaderDetector can be used to use the incoming `accept-language` header to determine what language to show users. 

By specification, HTTP headers are case insensitive, and it's common for different browsers and webservers to use different casings, for whatever reason.

`typesafe-i18n` currently uses a [case-sensitive comparison](https://github.com/ivanhofer/typesafe-i18n/blob/main/packages/detectors/src/detectors/server/accept-language-header.mts#L10) on the `accept-language` header, which doesn't work when the browser sends a header like: `Accept-Language: en`

### Reproduction

Super easy to repro: pass a header with different casing to the server and it won't detect the requested locale.

### Config

```JSON
{
   "adapter": "svelte",
   "$schema": "https://unpkg.com/typesafe-i18n@5.13.0/schema/typesafe-i18n.json"
}
```

**Comment by ivanhofer** [comment]
> ```
> const detectedLocale = detectLocale(
>    initAcceptLanguageHeaderDetector(req.headers.get('accept-language')),
> )
> ```

But here you have the exact same problem. You would also need to check for multiple cases.

---

Changing the interface to something other than the web-platforms native `Headers` object does not make sense.
It looks like the getter is already case-insensitive: (https://developer.mozilla.org/en-US/docs/Web/API/Headers/get#parameters)

Just changing [this](https://github.com/ivanhofer/typesafe-i18n/blob/main/packages/detectors/src/detectors/server/accept-language-header.mts#L12) to
```diff
-		(headers[headerKey] as string)
+		(headers.get(headerKey) as string)
```
should fix the problem.

**Comment by gkinsman** [comment]
> But here you have the exact same problem. You would also need to check for multiple cases.

This is using native `Headers.get`, which is case insensitive, so it would work - I realise that wasn't clear from my message! This is the solution I was suggesting 🙂.

In addition, it could be possible to support both a header string (pre-fetched from the Headers collection), and a request object, which would be typed as `{ headers: Headers }`, using the native Headers interface. Currently the input parameter to initAcceptLanguageHeaderDetector is typed as `({ headers }: ObjectWithHeaders, headerKey = 'accept-language')` which is not compatible with `Headers`.

**Comment by ivanhofer** [comment]
I want to keep it simple and don't provide multiple ways of doing things.

If you need special use-cases, you can always implement [your own custom detector](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/detectors#detectors-1).

Do you want to make the necessary change and open a PR?
