### ISSUE TITLE
"npm run typesafe-i18n" does'nt exit with svelte

### ISSUE THREAD

**Issue by blame2020** [ivanhofer/typesafe-i18n#452]
### Version

8.19.1

### Describe the bug

"npm run typesafe-i18n" does'nt exit for generate some files.
Is it expected behavior? 
```
$ npm run typesafe-i18n

> typesafe-i18n-demo-sveltekit@1.0.0 typesafe-i18n
> typesafe-i18n

[typesafe-i18n] version 5.13.0
[typesafe-i18n] generating files for TypeScript version: '4.8.x'
[typesafe-i18n] options: { adapter: 'svelte' }
[typesafe-i18n] watcher started in: './src/i18n/'
[typesafe-i18n] ... all files are up to date 
```

### Reproduction

The demo project can reproduce.
1.

```
git clone https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit
```

2.
```
npm install
```

3.
```
npm run typesafe-i18n
```

**Comment by ivanhofer** [comment]
Yes, the CLI will watch for changes during development and will update the types immediately.
If you don't wnt that behaviour, you can pass the [`--no-watch`option](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/generator#running-the-generator-in-cicd)

**Comment by blame2020** [comment]
Thanks!
