### ISSUE TITLE
Generator doesn't create files in new project

### ISSUE THREAD

**Issue by OliverJAsh** [ivanhofer/typesafe-i18n#454]
### Version

5.13.0

### Describe the bug

`npx typesafe-i18n --setup` is successful but no files have been generated:

```sh-session
$ mkdir test-app

$ cd test-app

$ yarn add typescript
yarn add v1.22.17
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ typescript@4.8.3
info All dependencies
└─ typescript@4.8.3
✨  Done in 0.52s.

$ npx typesafe-i18n --setup
[typesafe-i18n] version 5.13.0
[typesafe-i18n] See this link for more information on how to setup this project: https://github.com/ivanhofer/typesafe-i18n#options
✔ What is your base locale? … en
✔ What adapter do you want to use? › None
✔ Are you using esm modules in your project? › No / not sure
✔ Are you using TypeScript or JavaScript? › TypeScript
✔ Where do you want your locale files to be located? … ./src/i18n/
[typesafe-i18n] generated config file: '.typesafe-i18n.json'
[typesafe-i18n] installing dependencies ...
warning package.json: No license field
warning No license field
warning No license field
yarn add v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ typesafe-i18n@5.13.0
info All dependencies
└─ typesafe-i18n@5.13.0
Done in 0.24s.

[typesafe-i18n] WARNING: could not add 'typesafe-i18n' script to 'package.json'. You need to add it manually.

If you are using this project in a commercial environment please consider sponsoring 'typesafe-i18n':
https://github.com/sponsors/ivanhofer

$ ls
node_modules	package.json	yarn.lock

```

### Reproduction

See above.

**Comment by ivanhofer** [comment]
At the end of your log I can spot this:
>```
>[typesafe-i18n] WARNING: could not add 'typesafe-i18n' script to 'package.json'. You need to add it manually.
>```

Adding the script failed somehow.
You need to manually add it to your `package.json`

```json
{
   "scripts": {
      "typesafe-i18n": "typesafe-i18n"
   }
}
```

And then you can run

```bash
npm run typesafe-i18n
```

More information about the `generator` can be found [here](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/generator#generator).

**Comment by OliverJAsh** [comment]
Ah, thanks, I'll try that. I thought it was only a warning (not an error). Perhaps this could be made clearer?

**Comment by ivanhofer** [comment]
Well, it is not really required to add the script. It is just a recommandation.
You could also just use `npx typesafe-i18n` if you want.

**Comment by OliverJAsh** [comment]
@ivanhofer Ah, I think I was confused because [the documentation here](https://github.com/ivanhofer/typesafe-i18n/tree/7265f915e67f11b6b096b38fc6ca6a927c041805#get-started) makes it sound like the files will be generated as soon as you've ran `npx typesafe-i18n --setup`, but that's not the case—you also have to run `npx typesafe-i18n` or `npm run typesafe-i18n`.

**Comment by ivanhofer** [comment]
I have another Idea how to tackle this:

There exists an invisible character character called "ZeroWidthSpace" (`​`). We could use that character and inject it between each character on the `RootTranslation` type.

I have configured VS Code to show such special characters in red:

![image](https://user-images.githubusercontent.com/21335119/192691297-65f7b7eb-cd8f-4ae4-a495-55d5aa73100a.png)

If you search for "Hello" VS Code will only find it once. But you still would get the same hover-experience when moving the mouse over the key:

![image](https://user-images.githubusercontent.com/21335119/192691775-beaeeb1e-81e5-45c5-973c-af6888a08636.png)

What do you think?

**Comment by ivanhofer** [comment]
Ah right, the CLI gives you further instructions when everything was completed sucessfully. I'll make this more clear. Thanks for the feedback!

**Comment by ivanhofer** [comment]
https://github.com/ivanhofer/typesafe-i18n#get-started
