### ISSUE TITLE
Dynamic translations that use optional chaining return empty translations on SvelteKit production builds

### ISSUE THREAD

**Issue by Nickersoft** [ivanhofer/typesafe-i18n#467]
### Version

5.14.0

### Describe the bug

In my codebase, I've found it safer to use optional chaining when attempting to call dynamic translations that may or may not exist. For clarity, I'm referring to accessing translations like this:

```typescript
const myDynamicKey = "some-key";

$LL[myDynamicKey]?.()
```

The above works on SvelteKit/Vite's development server, but after building for production, the translations return empty. 

Yet if I drop the optional chaining:

```typescript
$LL[myDynamicKey]()
```

The translations work on both dev and prod. I'm not sure why, but I'm still pretty uncomfortable _not_ using optional chaining, as if an arbitrary string got passed in as a key and it couldn't find it, it would result in a runtime error. I'd rather gracefully display a fallback if something like that happened.

### Reproduction

I set up a reproduction [in this repo](https://github.com/Nickersoft/sveltekit-bugs). If you run `npm install`, then `npm run dev` you should see the following dynamic translations:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/2104129/193478314-23846ae3-97b6-4323-9e1c-5d03ffc8e017.png">

However, if you run `npm run build` (which just uses SvelteKit's default `auto` adapter), then `npm run preview`, the list items vanish and it returns a blank page:

<img width="152" alt="image" src="https://user-images.githubusercontent.com/2104129/193478350-2333e082-fae5-4cb4-a2ad-db5576ac96f1.png">

If you [drop the optional chaining](https://github.com/Nickersoft/sveltekit-bugs/blob/nickersoft/i18n-chaining/src/routes/%2Bpage.svelte#L10) and recompile, the translations will re-appear.

It's a super weird bug, and I'm not sure if this has to do with how these translations are managed or how SvelteKit bundles the code. Any help would be appreciated.

### Logs

No console errors, server or client side, as far as I can tell

### Config

```JSON
{
	"adapter": "svelte",
	"$schema": "https://unpkg.com/typesafe-i18n@5.14.0/schema/typesafe-i18n.json",
	"baseLocale": "en"
}
```

### Additional information

Tested using Node 18.9.0

**Comment by ivanhofer** [comment]
Hi @Nickersoft,
you don't have to worry about runtime errors. `typesafe-i18n` is smart enough to just output an empty string if a key does not exist. Just remove the optional chaining, it's fine.

**Comment by NimmLor** [comment]
Just experienced the same issue with a react Vite project.
