### ISSUE TITLE
"Cannot find module" in yarn monorepo setup

### ISSUE THREAD

**Issue by epicbytes** [ivanhofer/typesafe-i18n#472]
### Version

5.14.0

### Describe the bug

Hi! I ran into a problem when using turborepo, if the module is added to one application, then everything works as it should. But when added to the second, the module starts to give an error when both are started.

Applications are written in NextJS.

Both times the module is connected and initialized according to the instructions.

### Reproduction

install module
auto setup module
connected this to one more application in turborepo

### Logs

```sh
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Volumes/WORK/website/apps/admin/node_modules/typesafe-i18n/react' imported from /Volumes/WORK/website/apps/admin/.next/server/pages/_app.js
Did you mean to import typesafe-i18n/react/index.cjs?
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:404:11)
    at moduleResolve (node:internal/modules/esm/resolve:965:10)
    at defaultResolve (node:internal/modules/esm/resolve:1173:11)
    at nextResolve (node:internal/modules/esm/loader:173:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)
    at ESMLoader.import (node:internal/modules/esm/loader:536:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1059:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:21) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/'
}
```

### Config

```JSON
{
   "adapter": "react",
   "$schema": "https://unpkg.com/typesafe-i18n@5.14.0/schema/typesafe-i18n.json",
   "baseLocale": "en"
}
```

**Comment by ivanhofer** [comment]
Hi @epicbytes can you share the repository?

**Comment by epicbytes** [comment]
https://github.com/epicbytes/sample-bug

This is a monorepo recreated from scratch.
cd /apps/web and run yarn dev, then try to open it in browser

**Comment by ivanhofer** [comment]
I tried the example in StackBlitz and it works when adding a default value on this line

https://github.com/epicbytes/sample-bug/blob/main/apps/web/src/pages/index.tsx#L17

```diff
-const locale = context.locale as Locales;
+const locale = context.locale as Locales || baseLocale;
```

**Comment by ivanhofer** [comment]
I was now finally able to reproduce your issue.
I don't think this has anything to do with `turbo`.
It seems like an issue with `yarn` and how it installs dependencies in a monorepo setup. I haven't looked in detail but it seems that all dependencies are installed at the root `node_modules` folder. Therefore `Next.js` is not able to pick up the imports correctly.
I still wonder why other packages can be resolved correctly, but `typesafe-i18n` not...

Workaround for now: setting the [`generateOnlyTypes`-option](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/generator#generateOnlyTypes) to `true` and manually prefix all `typesafe-i18n` imports with `../../../../node_modules` to the the library where it is actually located.

**Comment by ivanhofer** [comment]
I have found [this issue](https://github.com/yarnpkg/yarn/issues/7572). It seems the issue is the "hoisting" of packages in `yarn`.
Changing the `workspace` config in `package.json` will fix the issue:
```diff
-  "workspaces": [
-    "apps/*",
-    "packages/*"
-  ],
+  "workspaces": {
+    "packages": [
+      "apps/*",
+      "packages/*"
+    ],
+    "nohoist": [
+      "**/typesafe-i18n",
+      "**/typesafe-i18n/**"
+    ]
+  },
```

**Comment by epicbytes** [comment]
Thanks, now it works as it should, it would be great to describe it in the documentation.

**Comment by ivanhofer** [comment]
I'll add a section to the FAQs

**Comment by ivanhofer** [comment]
added: https://github.com/ivanhofer/typesafe-i18n#cannot-find-module-in-yarn-monorepo-setup

**Comment by tinwritescode** [comment]
@ivanhofer I found the same issue happens on Nx monorepo. Is there anyone have solution?
