### ISSUE TITLE
Unlisted production dependency on "svelte" package

### ISSUE THREAD

**Issue by Nickersoft** [ivanhofer/typesafe-i18n#486]
### Version

5.15.0

### Describe the bug

I recently noticed that this package has an unmentioned production dependency on `svelte`, despite `svelte` being listed as a `devDependency` in both the [Svelte example repo](https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit) and [Svelte adapter](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/adapter-svelte). I came across it after pruning the dev dependencies from my SvelteKit project and having my bundle Node server fail to run.

I think this should be at least mentioned somewhere, or have the `package.json` files updated to reflect this dependency.

### Reproduction

I came up with a [minimal repro](https://github.com/Nickersoft/sveltekit-bugs/tree/nickersoft/i18n-svelte). Check out the `i18n-svelte` branch, and (with pnpm installed):

1. Run `pnpm install`
2. Run `pnpm run build`
3. Run `pnpm prune --prod`
4. Run `node build/index.js`

Trying to go to the given URL (`localhost:3000`), the server should fail, claiming it fails to find `svelte`. Moving `svelte` into the project's regular `dependencies` and rerunning the above makes it work.

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/2104129/197362694-e9f77dbc-e651-43de-bd21-412f4e073226.png">

### Logs

```sh
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'svelte' imported from /Users/tjnickerson/Documents/sveltekit-bugs/node_modules/.pnpm/typesafe-i18n@5.15.0_typescript@4.8.4/node_modules/typesafe-i18n/svelte/index.mjs
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:810:9)
    at moduleResolve (node:internal/modules/esm/resolve:859:20)
    at defaultResolve (node:internal/modules/esm/resolve:1074:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:425:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

### Config

```JSON
{
   "adapter": "svelte",
   "$schema": "https://unpkg.com/typesafe-i18n@5.15.0/schema/typesafe-i18n.json"
}
```

### Additional information

**Node Version:** `18.9.0`
**Svelte Version:** `3.44.0`

**Comment by ivanhofer** [comment]
Thanks, I have added a note to the docs: https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/adapter-svelte#notes
