### ISSUE TITLE
docs: Some links in the documentation are broken

### ISSUE THREAD

**Issue by artola** [ivanhofer/typesafe-i18n#492]
### Version

master

### Describe the bug

Some links in the documentation are broken. For example here (other places might happen too):

https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/exporter#example

```
An example implementation can be seen in the [exporter.ts-file](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/exporter/examples/exporter.ts).
```

### Reproduction

```
fails:
https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/exporter/examples/exporter.ts

works:
https://github.com/ivanhofer/typesafe-i18n/blob/main/packages/exporter/example/export.ts
```

https://github.com/ivanhofer/typesafe-i18n/blob/84500e188814dfdc3be206afc640e9a410873f72/packages/exporter/README.md?plain=1#L17

**Comment by ivanhofer** [comment]
Yes, there are probably more dead links. The only thing I can really do is, waiting for someone to find it and beeing that kind to report it. Thanks!

There really should be a GitHub action for detecting dead links in `markdown` files. I need to investigate this further.
