### ISSUE TITLE
Start node generator without watcher

### ISSUE THREAD

**Issue by Dzeri96** [ivanhofer/typesafe-i18n#55]
Hi,
When testing my app, I'd like to generate the Translation class in order to check type safety with `tsc`. A script in `package.json` would look something like this:
```
"scripts": {
    "test": "typesafe-i18n && tsc && npm run testOnly",
    ...
```
But the problem is that the watcher keeps running and the script never continues executing. Would it be possible to have a one-shot mode of the `typesafe-i18n` command? I'd contribute if you don't have time.

**Comment by ivanhofer** [comment]
Hi @Dzeri96,
I also need to implement this functionality for an upcoming feature. Just give me a few days :)

**Comment by ivanhofer** [comment]
You can checkout the new [`--no-watch`](https://github.com/ivanhofer/typesafe-i18n#running-the-generator-in-cicd) option in version 2.28.0

**Comment by Dzeri96** [comment]
Thanks for the fast implementation!  One suggestion I'd also make is to remove the `chokidar` dependency when running in one-shot mode. As far as I'm aware it's not needed in that case.

**Comment by ivanhofer** [comment]
It's not needed to run but I would need to create an own bundle for the --no-watch option.
And I think this would not work with the `bin` attribute inside `package.json`.
