### ISSUE TITLE
Next.js example does not work (`TypeError: localeTranslationLoaders[locale] is not a function`)

### ISSUE THREAD

**Issue by mateuszaliyev** [ivanhofer/typesafe-i18n#556]
### Version

5.7.0 (example) as well as 5.18.0 (latest)

### Describe the bug

This repository's official Next.js example does not work properly. Tested on both `5.7.0` (example version) as well as `5.18.0` (latest at the time of submitting the issue).

![image](https://user-images.githubusercontent.com/82393815/210184285-7fa2f58a-655e-426d-84d5-dbb4caf22f4b.png)

### Reproduction

1. Clone this repository.
2. `cd` into  `./packages/adapter-react/examples/nextjs`.
3. Run `npm install`.
4. Run `npm run dev`.
5. Open `http://localhost:3000` in the browser (this is where the error occurs).
6. Stop the development server.
7. Run `npm install typesafe-i18n@latest`.
8. Run `npm run dev`.
9. Open `http://localhost:3000` in the browser (bug is present even on the latest version).

### Logs

```sh
error - src\i18n\i18n-util.async.ts (18:8) @ importLocaleAsync
error - TypeError: localeTranslationLoaders[locale] is not a function
    at importLocaleAsync (webpack-internal:///./src/i18n/i18n-util.async.ts:32:82)
    at loadLocaleAsync (webpack-internal:///./src/i18n/i18n-util.async.ts:34:34)
    at getI18nProps (webpack-internal:///./pages/index.tsx:38:83)
    at Object.renderToHTML (C:\dev\typesafe-i18n\packages\adapter-react\examples\nextjs\node_modules\next\dist\server\render.js:451:26)
    at async doRender (C:\dev\typesafe-i18n\packages\adapter-react\examples\nextjs\node_modules\next\dist\server\base-server.js:912:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (C:\dev\typesafe-i18n\packages\adapter-react\examples\nextjs\node_modules\next\dist\server\base-server.js:1017:28)
    at async C:\dev\typesafe-i18n\packages\adapter-react\examples\nextjs\node_modules\next\dist\server\response-cache.js:69:36 {
  page: '/'
}
  16 |
  17 | export const importLocaleAsync = async (locale: Locales): Promise<Translations> =>
> 18 |  (await localeTranslationLoaders[locale]()).default as unknown as Translations
     |        ^
  19 |
  20 | export const loadLocaleAsync = async (locale: Locales): Promise<void> => {
  21 |  updateDictionary(locale, await importLocaleAsync(locale))
```

### Config

```JSON
{
   "adapter": "react",
   "$schema": "https://unpkg.com/typesafe-i18n@5.18.0/schema/typesafe-i18n.json"
}
```

### Additional information

Removing `default` locale from `next.config.js` resolves the issue.

**Before**

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  i18n: {
    locales: ['default', 'de', 'en', 'it'],
    defaultLocale: 'default',
  },
  reactStrictMode: true,
}

module.exports = nextConfig
```

**After**

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  i18n: {
    locales: ['de', 'en', 'it'],
    defaultLocale: 'en',
  },
  reactStrictMode: true,
}

module.exports = nextConfig
```

**Comment by ivanhofer** [comment]
Thanks @mateuszaliyev for opening this bug. I was not able to reproduce this. But I think it makes sense to remove the `default` value from the config. I have updated the example.

**Comment by Al-Ghoul** [comment]
Hello, I'm having the same issue; however it's a browser specific problem and I'm still digging to find the root of the issue
on Firefox Dev Edition it works perfectly, however on browsers like Brave (Chromium based web) it doesn't work.

Info:
 Brave, Version 1.52.126 Chromium: 114.0.5735.133 (64-bit)
 Firefox Dev Edition 115.0b7 (64-bit)
 
 Error message:
 `export const importLocaleAsync = async (locale: Locales): Promise<Translations> =>
> 17 |  (await localeTranslationLoaders[locale]()).default as unknown as Translations`

**Comment by ivanhofer** [comment]
@Al-Ghoul do you have different language settings in those browsers?

**Comment by Al-Ghoul** [comment]
Nah, I actually don't use auto-detection I'm also not using this repo's NextJS example, I'm using latest NextJS w\ App Directory\Routing. I use 'sub-path' i18n and I have just two locales ['ar', 'en'] for Arabic and English accordingly, However I found that browsers like Brave (not sure if chrome does the same since brave is chromium based) send an extra request, like site.com\favicon.icon even if u don't load an icon which conflicted with what I was using (i.e 'sub-path'), the server expected first sub-path to be the targeted locale, i.e site.com\ar, so I just ignored favicon(s) sub requests which fixed the issue, other than that this lib works perfectly, thanks for your time and efforts!

- Regards, A .G
