### ISSUE TITLE
Usage with typescript `nodenext`

### ISSUE THREAD

**Issue by AlexXanderGrib** [ivanhofer/typesafe-i18n#577]
### Version

^5.19.1

### Describe the bug

It is not possible to generate i18n types, with .js imports. Typescript is mad

### Reproduction

Set `moduleResolution` in tsconfig.json to `nodenext` and you will get

`TS2834` Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path. 

### Config

```JSON
{
   "esmImports": false,
   "$schema": "https://unpkg.com/typesafe-i18n@5.19.1/schema/typesafe-i18n.json",
   "baseLocale": "en"
}
```

**Comment by ivanhofer** [comment]
That's why the [`esmImports` config option](https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/generator#esmimports) exist.
Why did you disable it?

**Comment by AlexXanderGrib** [comment]
I do not remember what the problem was for me to disable `esmImports`, but now it works, thanks
