### ISSUE TITLE
ZWSP in RootTranslation generated comments

### ISSUE THREAD

**Issue by azdanov** [ivanhofer/typesafe-i18n#585]
### Version

5.17.0

### Describe the bug

In `src/i18n/i18n-types.d.ts` RootTranslation the comments are generated with a strange symbol [ZWSP](https://en.wikipedia.org/wiki/Zero-width_space).
But in TranslationFunctions it's all good.

<img width="1904" alt="Screenshot 2023-02-03 at 15 34 56" src="https://user-images.githubusercontent.com/6123841/216616446-ae3bd075-97ef-4f93-af1b-233fa73c4ceb.png">

### Reproduction

I've used this https://github.com/ivanhofer/typesafe-i18n/tree/main/packages/adapter-react/examples/react and just ran a standard install.

**Comment by azdanov** [comment]
The problem is that some IDEs are very precise in which symbols they display.
<img width="502" alt="Screenshot 2023-02-03 at 15 40 30" src="https://user-images.githubusercontent.com/6123841/216617549-fb2be931-f96d-4953-9807-6c18afcffc4a.png">

**Comment by ivanhofer** [comment]
This is intended.
If you search in your IDE for "Hello", you are probably looking for the key inside `TranslationFunctions`. You can `CTRL + [click]` on it to go to the place where you use it in your code. The "zero width space" character prevents the search results showing it twice.

Do you have a use-case why you would need it to display the message in that file without the special characters?

**Comment by azdanov** [comment]
> This is intended.

Oh, then it's all good 😄 
Why I created this issue because it looked strange, as in the previous screenshot and I didn't know that it's to prevent the global search from picking those results.
