### ISSUE TITLE
Default translations not defined on first render

### ISSUE THREAD

**Issue by aelesia** [ivanhofer/typesafe-i18n#59]
Currently facing an issue where Jest fails to load translations despite having a `baseLocale` and `initialLocale` set.

The problem comes from `react-adapater.tsx`, where `currentLocale` and `LL` are not initialized on first render.

Normally this isn't an issue when viewing the webpage as it re-renders almost immediately, but Jest only captures the first render and fails due to it not being set.

I've modified the code to the following in my project as a temporary fix:

_typesafe-i18n/packages/adapter-react/src/react-adapter.tsx_
```tsx
    const locale = props.initialLocale ?? baseLocale;

    const [isLoadingLocale, setIsLoadingLocale] = useState<boolean>(false);
    const [currentLocale, setCurrentLocale] = useState<L>(locale);
    const [LL, setLL] = useState<TranslationFunctions>(
      i18nObject<L, T, TF, F>(
        locale,
        (getTranslationForLocale as TranslationLoader<L, T>)(locale),
        initFormatters(locale) as any
      )
    );

```

**Comment by ivanhofer** [comment]
You are loading your locales synchronously, am I right?
This code is written to support both sync and async loading of locales. I think your solution would not work with async locale fetching.

I'm no react expert but I will check if I can find a better solution to have the first render show the translations.
Thanks for your feedback!

**Comment by aelesia** [comment]
Hi yup, I'm loading my locales synchronously, and yup, I don't think it will work with async locale fetching. I'll try to explore a way to make it work with both.

_____

However I also had problems with `loadLocalesAsync: true` even with vanilla code with no modifications. React kept complaining that LL.<translation> is `undefined`. After changing it to `loadLocalesAsync: false` it worked. Wasn't sure if it was the library or if it was my own project so I didn't open an issue for that yet. I'll see if I can start another blank project to replicate the issue.
