### ISSUE TITLE
ReferenceError: dirname is not defined with on version 5.23.1

### ISSUE THREAD

**Issue by vchirikov** [ivanhofer/typesafe-i18n#592]
### Version

5.23.1

### Describe the bug

`vite dev` throws the error: 
```
failed to load config from _________\vite.config.ts
error when starting dev server:
ReferenceError: dirname is not defined
    at file:///_____________/node_modules/.pnpm/typesafe-i18n@5.23.1_typescript@4.9.5/node_modules/typesafe-i18n/utils/index.mjs:8:19
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```
### Reproduction

run vite dev + typesafe-i18n

### Additional information

versions:
```
    "vite": "^4.1.1",
    "vite-plugin-solid": "^2.5.0",
    "vite-plugin-ssr": "^0.4.77",
    "typesafe-i18n": "^5.23.1",
```

~~Works fine with `5.21.0`~~
investigating which update breaks the `vite dev`

**Comment by ivanhofer** [comment]
It is probably an issue with the transformation of `lodash.merge`.
It did work in my test application. I would need a test repo to investigate it further. Can someone please set one up for me?

**workaround: revert to version `5.22.0`**

**Comment by ivanhofer** [comment]
I have released `5.23.2`. Please try it and let me know if it works.

**Comment by Cluster2a** [comment]
@ivanhofer, `5.23.2` seems to be good!

**Comment by ivanhofer** [comment]
> The error is gone, but for some reason, I am getting TS errors

Really strange. Nothing has changed affecting this part of `typesafe-i18n`. Try to restart your IDE.

**Comment by Cluster2a** [comment]
@ivanhofer, I edited my comment - it seems to be good now.

**Comment by proddy** [comment]
works again, thanks.
