### ISSUE TITLE
extendDictionary is not switching translations properly

### ISSUE THREAD

**Issue by Cluster2a** [ivanhofer/typesafe-i18n#618]
### Version

5.24.1

### Describe the bug

If creating `en-US` as an extension of `en`, via `extendDictionary`, the locale switcher is not switching between `en` and `en-US`:

https://user-images.githubusercontent.com/84905165/222242546-a487a4a9-519e-436e-a56b-ded3c88a1299.mp4

### Reproduction

Use the svelteKit example app (https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit) and update all dependencies (`ncu -u`) and add en-US:

![image](https://user-images.githubusercontent.com/84905165/222242776-80f12f15-1e39-403d-a7a9-b78694b51024.png)

**Comment by ivanhofer** [comment]
My bad. I assumed lodash.merge works in an immutable way. But instead it alters the orginal object. I will need to find a replacement for this line: https://github.com/ivanhofer/typesafe-i18n/blob/main/packages/utils/src/extendDictionary.mts#L24

**Comment by ivanhofer** [comment]
It seems `merge({}, obj1, obj2)` is the solution.

**Comment by ivanhofer** [comment]
Should be fixed in version `5.24.3`. Thanks for reporting this issue.

**Comment by Cluster2a** [comment]
Thanks for the quick fix!
