### ISSUE TITLE
First time --setup-auto mangling packages.json

### ISSUE THREAD

**Issue by coldino** [ivanhofer/typesafe-i18n#631]
### Version

5.24.2

### Describe the bug

The automation that adds the `typesafe-i18n` line to `scripts` in package.json seems to struggle when there are (quoted) closing curly brackets in a previous script entry.

### Reproduction

In packages.json:
```json
	"scripts": {
		"prisma:repl": "ts-node --project prisma/tsconfig.json --compilerOptions '{ \"module\": \"node16\" }'"
	},
```

Then simply:
```sh
npx typesafe-i18n --setup-auto
```

Results in mangled JSON format:
```json
	"scripts": {
		"prisma:repl": "ts-node --project prisma/tsconfig.json --compilerOptions '{ \"module\": \"node16\",
		"typesafe-i18n": "typesafe-i18n" }'"
	},
```

### Logs

```sh
Nothing special. All completes succesfully.
```

### Config

```JSON
Not relevant at this stage.
```

**Comment by ivanhofer** [comment]
Fixed in version `5.24.3`.

Thanks for your help!
