### ISSUE TITLE
Not supported on older browser versions due to Intl.PluralRules & Intl.Locale

### ISSUE THREAD

**Issue by aelesia** [ivanhofer/typesafe-i18n#65]
https://caniuse.com/?search=PluralRules

My main phone is an iPhone 6S running 12.1.1. It's not able to load the webpage as it does not have Intl.PluralRules & Intl.Locale. As such I'm using polyfills for both:

```
import "@formatjs/intl-pluralrules/polyfill";
import "@formatjs/intl-locale/polyfill";
```

This isn't really a bug or problem with the library. But perhaps the library could either call an alternative method or provide a section with instructions on how to solve this issue on older browsers:

```
TypeError: undefined is not a constructor (evaluating 'new Intl.PluralRules(locale)')
getTranslateInstance
src/util.object.ts:20
  17 | // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types, @typescript-eslint/no-explicit-any
  18 | function i18nObject(locale, translations, formatters = {}) {
  19 |     return createProxy(getTranslateInstance(locale, translations, formatters));
20 | }
  21 | exports.i18nObject = i18nObject;
  22 | const createProxy = (fn, prefixKey) => new Proxy((prefixKey ? fn.bind(null, prefixKey) : {}), {
  23 |     get: (_target, key) => createProxy(fn, prefixKey ? ${prefixKey}.${key} : key),
```
_____

EDIT: I updated to 2.34.0 and tried it again. On 2.34.0, it doesn't outright crash but instead it shows the translation label keys. In a way it's good because it still renders and is still usable. In other ways it's bad because it fails silently.

**Comment by ivanhofer** [comment]
Hi @aelesia;
I'm aware that these functions are not supported in older browsers. I don't want to include the polyfills in the library itself, so like you already guessed, you need to include them by yourself.

The only thing I could do is updating the READMRE file to make it clear.
Do these two polyfills you mentioned work on older browsers?

**Comment by aelesia** [comment]
Hi! Yup I've tested on my iPhone 6S running 12.1.1. It works after adding both of these lines:

```javascript
import "@formatjs/intl-pluralrules/polyfill";
import "@formatjs/intl-locale/polyfill";
```

https://formatjs.io/docs/polyfills/intl-pluralrules/
https://formatjs.io/docs/polyfills/intl-locale

**Comment by ivanhofer** [comment]
Ok, thanks! I will update the README file

**Comment by ivanhofer** [comment]
@aelesia nut sure why you need to include both polyfills?
I just checkt the [formatjs website](https://formatjs.io/docs/polyfills) and it seems you would only need this polyfill:
https://formatjs.io/docs/polyfills/intl-pluralrules/

`typesafe-i18n` by default only uses `Intl.PluralRules`. Additional there exist two optional [`formatters`](https://github.com/ivanhofer/typesafe-i18n#formatters) that use the `Intl.NumberFormat` and `Intl.DateTimeFormat` functions. But it seems these two are included into the `Intl.PluralRules` polyfill.

Can you please confirm that it works only with the single polyfill?
