### ISSUE TITLE
Importing module from alias or different paths gives "Cannot find module"

### ISSUE THREAD

**Issue by jessielaf** [ivanhofer/typesafe-i18n#651]
### Version

5.20.0

### Describe the bug

I have a turborepo mono repo which uses pnpm to install all packages. If I try to import common translations in my component package, I get the following error when I try to run the `typesafe-i18n` command: 

```
[typesafe-i18n] ERROR: import failed for /Users/jessie/projects/jcbdevelopment/jcb/apps/boiler/node_modules/typesafe-i18n/temp-output/0/i18n/en/index.js Error: Cannot find module '@jcb/translations'
Require stack:
- /Users/jessie/projects/jcbdevelopment/jcb/node_modules/.pnpm/typesafe-i18n@5.20.0_typescript@4.9.5/node_modules/typesafe-i18n/temp-output/0/i18n/en/index.js
[typesafe-i18n] ERROR: could not read default export from base locale file 'en'
```

However, when I use my typescript aliases such as `$i18n/en/test.js` (which is in the same project) I get the same error:

```
[typesafe-i18n] ERROR: import failed for /Users/jessie/projects/jcbdevelopment/jcb/apps/boiler/node_modules/typesafe-i18n/temp-output/1/i18n/en/index.js Error: Cannot find module '$i18n/en/test'
Require stack:
- /Users/jessie/projects/jcbdevelopment/jcb/node_modules/.pnpm/typesafe-i18n@5.20.0_typescript@4.9.5/node_modules/typesafe-i18n/temp-output/1/i18n/en/index.js
[typesafe-i18n] ERROR: could not read default export from base locale file 'en'
```

When I use relative imports such as `./test.ts` it does work. Is there any way I can import my translations from a package without using relative imports?

I have not tested if this is also the case for non-monorepo setups.

### Reproduction

- Create a monorepo with svelte
- Follow the svelte setup for typesafe-i18n
- Create a typescript package with common translations
- Import typescript file into the translations file of typesafe-i18n. For example `en.ts`.

### Config

```
{
   "adapter": "svelte",
   "$schema": "https://unpkg.com/typesafe-i18n@5.20.0/schema/typesafe-i18n.json"
}
```

**Comment by jessielaf** [comment]
I just tested without the monorepo and the issue also occurs. It seems like only relative paths are working.

**Comment by ivanhofer** [comment]
Right, this is a limitation of the current process on how translations need to be parsed in order to generate the type definitions.

Can you please take a look at the compiled`typesafe-i18n` code and add the `path` option to `createProgram` (https://github.com/ivanhofer/typesafe-i18n/blob/main/packages/generator/src/parse-language-file.mts#LL85) and see if it works?

**Comment by jessielaf** [comment]
@ivanhofer I kind of fixed it by moving the typesafe-i18n library to my translations package. Maybe even a cleaner solution. It is more coupled to typesafe-i18n, but I don't really mind that. Anyway, I will close this issue. Thanks for this library!

**Comment by ivanhofer** [comment]
Great that you found a solution!
