### ISSUE TITLE
Docs: vscode i18n-ally integration needs additional steps.

### ISSUE THREAD

**Issue by Lorenium** [ivanhofer/typesafe-i18n#653]
I've integrated i18n-ally extension exactly like in the docs but I was getting the error mentioned here: https://github.com/lokalise/i18n-ally/issues/709

They've provided a solution in that issue which is:

`cd ~/.vscode/ extensions/lokalise.i18n-ally-2.8.1/`
`yarn add -D ts-node`

After doing that, I was getting the error mentioned here:
https://github.com/lokalise/i18n-ally/issues/709#issuecomment-1229157767

The solution to that is to add a phantom package.json file :
`touch src/i18n/package.json`

I made a file like this (maybe it could be empty and still work?)
`{
	"name": "phantom-i18n"
}`

And that finally fixed it. Seems like a lot of work to integrate it, hope the extension gets updated/forked in the near future.

**Comment by ivanhofer** [comment]
Can you please add a comment with your workaround here: https://github.com/lokalise/i18n-ally/issues/678?

i18n-ally is unmaintained and the official support for `typesafe-i18n` won't get merged.
I don't want to spend my time on those issues anymore.

In the future you should take a look at https://inlang.com/, which will offer an IDE extension soon that can be replac som ekey functionality of i18n-ally.
