### ISSUE TITLE
'isLocaleLoading' store not available in svelte adapter

### ISSUE THREAD

**Issue by thomasmol** [ivanhofer/typesafe-i18n#665]
### Version

5.24.3

### Describe the bug

In the docs of the svelte adapter it says there is a ```isLocaleLoading``` function. However, it does not seem to be implemented/available.

### Reproduction

Install latest package in a svelte(kit) app, import 'isLocaleLoading' like in the docs.

### Config

```JSON
{
   "adapter": "svelte",
   "$schema": "https://unpkg.com/typesafe-i18n@5.24.3/schema/typesafe-i18n.json"
}
```

**Comment by ivanhofer** [comment]
Thanks for letting me know. I have removed this outdated section from the readme.

If you need this behaviour, you can implement it yourself. The function `loadLocaleAsync` returns a promise and you should be able to know whenloading a locale has completed and manually set a variable.
