### ISSUE TITLE
Not working with NextJS 13 because Context components need to be client component "use client"

### ISSUE THREAD

**Issue by goughjo02** [ivanhofer/typesafe-i18n#681]
### Version

5.24.3

### Describe the bug

make a new nextjs 13 app. add typesafe-i18n. wrap the app in the provider (even inside a component that is already a client comepont) and it throws an error. createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component

### Reproduction

I cannot make one right now but the error is very simple to reproduce and explain

**Comment by ivanhofer** [comment]
Îf I understand it correctly, then `"use client"` should be added to the top of that file, right?
https://github.com/ivanhofer/typesafe-i18n/blob/main/packages/adapter-react/src/index.tsx

Can you test if it works if you add that line to the compiled output?
The path should be `react/index.mjs` or `react/index.cjs`

**Comment by goughjo02** [comment]
hey, @ivanhofer ... sorry about this but when i tried to make a minimal reproducible example, the error was not happening anymore 😬. It must have been my mistake as i was rushing yesterday so my apologies for that. here is the reproduction that i made that does not have the error https://github.com/goughjo02/nextjs-13-typesafe-i18n-sample

However, this example is showing another error. **the strings are empty**... even though there are no typescript errors and i do not see any warning or errors anywhere. if you have a minute would you be able to run this and see why you think the translation is missing? I was having the same issue running this in ModernJS. I have a suspicion it might have something to do with pnpm. 

many thanks.

p.s. as the original bug report appears to not be valid, feel free to close this. i could make another issue for this other bug. thanks again

**Comment by ivanhofer** [comment]
See here: https://github.com/ivanhofer/typesafe-i18n/blob/main/README.md#calling-llkey-renders-an-empty-string
