### ISSUE TITLE
i18n-util.async.ts does note load namespaces

### ISSUE THREAD

**Issue by planerist** [ivanhofer/typesafe-i18n#700]
### Version

5.25.1

### Describe the bug

The generated loadLocaleAsync loads only top level localizations ignoring namesapces:

```js
export const loadLocaleAsync = async (locale: Locales): Promise<void> => {
  updateDictionary(locale, await importLocaleAsync(locale))
  loadFormatters(locale)
}
````

Although loadNamespaceAsync is generated but never called

### Reproduction

Just any project with namespaces generated the code above

**Comment by ivanhofer** [comment]
You need to call the function yourself when you want to load a namespace.
