### ISSUE TITLE
Error: Cannot find module 'chokidar'

### ISSUE THREAD

**Issue by hmmhmmhm** [ivanhofer/typesafe-i18n#73]
```json
"typesafe-i18n": "^2.36.0"
```

i used to install `npm i -D typesafe-i18n` on my project and i wroted command script in my package.json
```json
"scripts": {
    "i18n": "typesafe-i18n"
},
```
and i found like this error messages
```
Error: Cannot find module 'chokidar'
Require stack:
- /Users/hm/Desktop/Workspace/personal/polyger/node_modules/typesafe-i18n/node/generator.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
```

**Comment by hmmhmmhm** [comment]
i installed chokidar using command manually `npm i -D chokidar`, and yes it works.. but i think `chokidar` is might be append devDependencies, not the `peerDependencies`

**Comment by ivanhofer** [comment]
You are right!. Thanks,
Not sure why, but I somehow thought that `chokidar` itself is a dependency of `typescript` and will be installed anyways.
I will fix this.

**Comment by hmmhmmhm** [comment]
@ivanhofer  oh... It seems that this issue is still occurring on typesafe-i18n@2.37.4. I think we need to add chokidar as a dependencies.

**Comment by ivanhofer** [comment]
How do you install your dependencies?
`chokidar` is in the list of devDependencies and should also be there when you install `typesafe-18n`

**Comment by hmmhmmhm** [comment]
@ivanhofer Oh, I'm sorry. It was installed properly after installation.
