### ISSUE TITLE
Sveltkit is using shared global store server-side (SSR)

### ISSUE THREAD

**Issue by cristovao-trevisan** [ivanhofer/typesafe-i18n#746]
### Version

5.26.2

### Describe the bug

Current svelte implementation is using a global LL store, which is shared server side thus may cause inconsistent language with SSR.
As per [sveltekit docs # avoid shared state](https://kit.svelte.dev/docs/state-management#avoid-shared-state-on-the-server) stores should never be global (should not be exported in .ts and .js files), but the [current code does so](https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/blob/202b5dd4cfbda3587b22549f3a6384f42814530a/src/i18n/i18n-svelte.ts#L8C139-L8C139):

```ts
const { locale, LL, setLocale } = initI18nSvelte<Locales, Translations, TranslationFunctions, Formatters>(loadedLocales, loadedFormatters)
```

There are two options to fix this problem that I'm aware off:
- use context to set the store in layout.svelte (and further acquire LL from the context again)
- use the $app.data (PageData) to set the store in layout.ts

Context usage can also be simplified using components, for example:
- +layout.svelte
```svelte
<LangProvider locale={initLocale()}>
  <slot />
</LangProvider>
```
- +page.svelte
```svelte
<Locale let:LL>
  {LL.HI()}
</Locale>
```
### Reproduction

This is hard to reproduce consistently since it's a race condition (multiple requests with different languages at the same time).
The thing is, as per kit's docs, stores should not be global, so the bug is there as long as there is a global store being used.

**Comment by cristovao-trevisan** [comment]
Related issue at similar lib: https://github.com/cibernox/svelte-intl-precompile/issues/39

**Comment by Cluster2a** [comment]
This project is not maintained anymore - [739](https://github.com/ivanhofer/typesafe-i18n/issues/739).
