### ISSUE TITLE
Formatters typing generates one param type per translation file entry

### ISSUE THREAD

**Issue by mullwaden** [ivanhofer/typesafe-i18n#75]
First of all, thanks for a fantastic library, its fantastic to be able to mix TS and i18n in this way.

I'm running into a rather weird issue. The generated formatter type creates one input param type per translation file entry.

```
// i18n-types.ts

export type Formatters = {
	'requestTitle': (value: Request | Request) => unknown
	'userName': (value: User | User | User | User | User | User) => unknown
	'userNameAndOrg': (value: User) => unknown
}
```

As you can see, ``User | User | User | User | User | User``. One User for every ``{sender:User|userName}`` in the translation file.

**Comment by ivanhofer** [comment]
Hi @mullwaden,
thanks for filing this issue.

Should be fixed in version `2.37.1`
