### ISSUE TITLE
Make an example for NextJS

### ISSUE THREAD

**Issue by IRediTOTO** [ivanhofer/typesafe-i18n#77]
Hi, I am trying to use your pack with NextJS :) It's so great but can you make an example to show what is the best option for nextjs?
I am using like this
In my `_app.js`
```
const App = ({ Component, pageProps, router }: AppProps) => {
    const detectedLocale = detectLocale(() => router.locales)
    
   return (
      <TypesafeI18n initialLocale={detectedLocale}>
            <Component {...pageProps} />
      </TypesafeI18n>
   )
}


```

in `button-change-language`

```
const LanguageChange = (props) => {
    const { LL, setLocale } = useContext(I18nContext)
    const router = useRouter()

 useEffect(() => {
        setLocale(router.locale as Locales) // change locale when router.locale change
    }, [router.locale])

return <button onclick={()=>router.push({
            pathname:router.asPath,
            locale:'it'

})}>click me to change</button>
}
```

use it
```
    const { LL } = useContext(I18nContext)

return (
<p>{ LL.login()}}</p>
)

```
Everything look work good but Is this the right way to use ?
I don't understand what is the benerfit of L,LL,LLL. is LL the best option? 
Will the translate text fit SSR of NextJS, text will be static when run build ?

**Comment by IRediTOTO** [comment]
Look like your pack just run on client, not on server. Text is not static :( it run on browser, I would love it run when i `npm run build to get static text`
![image](https://user-images.githubusercontent.com/15695252/131703436-9935881f-9b20-4df7-9a39-d8225f77118c.png)

**Comment by IRediTOTO** [comment]
Finally, i config it out :) ` "loadLocalesAsync": false,`
please introduce your pack in NextJS group. Yours is the best, I think. 
One more problem, if I have thousands of lines, can we separate files?

**Comment by Glinkis** [comment]
Huh. Why was I mentioned?

**Comment by ivanhofer** [comment]
Hi @IRediTOTO,
thanks for documenting your configuration.
I never have used Next.js on my own yet, but it seems you figured everything out on your own 👍
I will update the examples to include a Next.js demo
