### ISSUE TITLE
Best way to separate files

### ISSUE THREAD

**Issue by IRediTOTO** [ivanhofer/typesafe-i18n#78]
Hi, if translation file have thousands of lines. What will you do?
I am using like this, but it look like a good way.
```
import type { BaseTranslation } from 'typesafe-i18n'
import { langCheckOut } from './lang-checkout'

const en: BaseTranslation = {
    ...langCheckOut,
}

export default en
```

file: lang-checkout.ts 
```
import { BaseTranslation } from 'typesafe-i18n'

export const langCheckOut: BaseTranslation = {
    clickToChangeLanguage: 'Click to change Language',
    login: 'Login',
    bankName: 'Bank name',
    transferAccordingToTheFollowingInformation:
        'Transfer according to the following information',
    accountNumber: 'Account number',
    loginToContinue: 'Login to continue',
    showPaymentInfo: 'Show Payment Info',
    choosePaymentMethod: 'Choose payment method',
    checkout: 'Checkout',
}


```

**Comment by ivanhofer** [comment]
Hi @IRediTOTO,
managing bigger dictionaries can be hard.
You should structure your translations like it suits best for you.

You could create smaller "feature" -packs and include them inside the `index.js`file like in your example above.

What I recommemd to do us nesting the translations:
you will find it probably easier to navigate troug an object structure then a flat list with a few hundred translations:

```diff
import type { BaseTranslation } from 'typesafe-i18n'
import { langCheckOut } from './lang-checkout'
const en: BaseTranslation = {
-   ...langCheckOut,
+  checkout :...langCheckOut,
}
export default en
```

you then would access these translations via `{LL.checkout.bankName}` and you could have another feature of you application have also a translation `bankName` and you would access it via `{LL.otherFeature.bankName}`

Does this info help?
