### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lisamburns** [ivanhofer/typesafe-i18n#79]
I tried out this library and it's great. I am not sure that I can use it in one of my projects though as I don't see any OSS licensing. Could you add a License file so we know what the licensing is?

**Comment by ivanhofer** [comment]
Hi @lisamburns,
thanks for your question! It is **MIT**.
Until now I only had set the license property inside `package. json`.
Now also a `LICENSE` file is included in the project root to make it more clear.
