### ISSUE TITLE
Optional parameters in translations

### ISSUE THREAD

**Issue by mullwaden** [ivanhofer/typesafe-i18n#86]
### Describe the bug

Optional parameters seem to be available, but they do not work, no value is passed along to the translation formatters.

### Reproduction

```
// somewhere in the code
translation.dueDate({ dueDate: new Date() });

// the translation file
dueDate: "Project due date: {dueDate?:Date|date_DATE}",

// the formatter
date_DATE: (date) => {
  if (!date) {
    return "n/a";
  }
  return moment(date).format(MOMENT_FORMATS.DATE);
},
```

This will return ``Project due date: n/a`` although the types look correct and a date is sent along.

**Comment by ivanhofer** [comment]
Actually, I never have thought about optional parameters ^^
I am really surprised that the type-system works out-of-the-box.
But the value doesn't get output. I will fix that

**Comment by ivanhofer** [comment]
optional parameters are now supported in version `2.41.0`
