### ISSUE TITLE
Generated types seem to be incorrect?

### ISSUE THREAD

**Issue by Evertt** [ivanhofer/typesafe-i18n#99]
### Describe the bug

I didn't do anything special as far as I'm aware. I just wanted to try out the `HI` translation that I saw in the readme.

So my base translation file, at `/src/i18n/en/index.ts` looks like this:

```typescript
import type { BaseTranslation } from 'typesafe-i18n'

const en: BaseTranslation = {
  HI: "Hello {name:string}"
}

export default en
```

And then I tried to write the dutch translation file at `/src/i18n/nl/index.ts` like this:

```typescript
import type { Translation } from "../i18n-types"

const nl: Translation = {
  HI: "Hallo {name:string}"
}

export default nl
```

And then I got the following error.

![image](https://user-images.githubusercontent.com/1267282/136145676-24c586d7-e99f-4c27-b94e-114bafa21204.png)

### Reproduction

See the previous paragraph.

In case you're interested, this is what my `/src/i18n/i18n-types.ts` file looks like:

```typescript
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import type { LocalizedString } from 'typesafe-i18n'

export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'nl'

export type Translation = {
	/**
	 * Hello {name}
	 * @param {string} name
	 */
	'HI': RequiredParams1<'name'>
}

export type TranslationFunctions = {
	/**
	 * Hello {name}
	 */
	'HI': (arg: { name: string }) => LocalizedString
}

export type Formatters = {}

type Param<P extends string> = `{${P}}`

type Params1<P1 extends string> =
	`${string}${Param<P1>}${string}`

type RequiredParams1<P1 extends string> =
	| Params1<P1>

```

I'm on Typescript 4.4.3 in case that matters.

### Config

```json
{
  "adapter": "svelte",
  "loadLocalesAsync": false
}
```

**Comment by ivanhofer** [comment]
hi @Evertt,
the type `string` is only needed for the base locale to tell the generator what type that argument should be. It does not make that much sense to include that type also in all the translations. Your `nl`-translation should look like:

```typescript
import type { Translation } from "../i18n-types"

const nl: Translation = {
  HI: "Hallo {name}"
}

export default nl
```
